### ISSUE TITLE
Find and install theme

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-mtsclovischamber#1]
URL: mtsclovischamber.editllc.com/wp-admin

I already shared the creds with you via lastpass.

Find a free WP theme and install it

Here is the current LIVE site: http://www.clovischamber.com/

due: 10-16-15 5p

**Comment by rodneystrong** [comment]
Hold off on this one for now because I still have to go through the notes to give you a better idea of what kind of theme to find. Don't worry about the due date; I'll update it once I've given you a clear idea about the direction of the site.

**Comment by jperez4509** [comment]
I just accepted the last pass info and it does not show the username.

**Comment by rodneystrong** [comment]
@jperez4509 crap! sorry about that. I updated the lastpass creds, but it follows the usual pattern of usernames. let me know if you still don't see it.

**Comment by rodneystrong** [comment]
ok, this issue is good to go now, I've updated the due date

**Comment by jperez4509** [comment]
Done. I installed this theme: https://wordpress.org/themes/vantage/
