### ISSUE TITLE
Implement all content

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-mtsclovischamber#2]
Here's a word doc we got from client that explains in good detail how they want the site structured and what content they want where. 

[Home Page.docx](https://github.com/EditLLC/client-mtsclovischamber/files/14532/Home.Page.docx)

due:
10-19-15    3p

**Comment by rodneystrong** [comment]
Here are the assets for the site: https://drive.google.com/open?id=0B88_mCI0OTGkWDAzOWJuUm9uajQ

**Comment by jperez4509** [comment]
@rodneystrong Do you have the google account info for this client. I need to get API for the Google Calendar Plugin

**Comment by rodneystrong** [comment]
that portion is still 'waiting on client'. followed up yesterday and today in slack with shel and chris.

**Comment by jperez4509** [comment]
@rodneystrong This site is taking longer than I thought. There are 28 pages on there current site plus there blog. Currently I have completed 6 in the last two days. Just giving you an update. How will I create a join right now form like they have here (http://www.clovischamber.com/membership/join) and a directory like here (http://www.clovischamber.com/membership/)

**Comment by rodneystrong** [comment]
I understand. 

But I dont understand your last statement of "how will i create a join right now form like they have here". 

Could you please clarify?

**Comment by jperez4509** [comment]
Done. all content has been added to site.
