### ISSUE TITLE
Design critique from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-mtsclovischamber#3]
>It's looking good. We'd like to see some more color/style applied here and there on the home page. Here are some things to tighten up on the concept:

1. We'd like floating text on each slider. I gave you a version of each graphic without words so that you could do this. Maybe you're already working on this, but I wanted to make certain...

2. Move the sponsors up the page. Only feature one at a time & preferably in color. (You can exclude Artco from the current logos - as they are no longer a viable sponsor. I'll see if I can't get an updated list from the Chamber to share with you.) We'd like this positioned either right below the slider or below the Welcome section/text. We can talk about alternative ideas here - but I know this needs to be a little more prominent and should also include text stating "Support Our Sponsors."

3. Can we use some icons or photos to spruce up the membership bullet points? Or color - I'm open to ideas, but think it needs more oomph.  (We geek out over cool parallax effects...) 

4. Can you try a horizontal Twitter feed so that it stretches end-to-end? Perhaps scrolling through 3 most recent tweets?

5. Are you okay with the calendar? What options exist for ways to display this?

6. We also need to embed the COC Tourbook from the existing home page within the community section.

I'm going through more, and am putting internal page notes together to send you, but wanted to share the initial thoughts. Sorry I didn't get this over last week - it was completely crazy. More coming in a few hours...

due:
10-28-15    5p

**Comment by jperez4509** [comment]
Did you ever receive the credentials for the calendar?

**Comment by jperez4509** [comment]
@rodneystrong  I found a widget that seems to do what they are requesting but I need API access, can you get there twitter credentials so I can do this.

**Comment by rodneystrong** [comment]
Never got the creds. This is for google calendar? You'll also need twitter creds? I'll ping client. Actually, could you find me a link with instructions for getting the API key for google calendar and Twitter so I can send it to the client? They might hesitate to hand over credentials.

**Comment by jperez4509** [comment]
Yes this is for a google calendar plugin, the link with instructions on how to use is here: http://wpdocs.philderksen.com/google-calendar-events/getting-started/api-key-settings/?utm_source=gce_lite&utm_medium=settings_link&utm_campaign=docs . The instructions for the Twitter API are attached as an image: 
<img width="1199" alt="screen shot 2015-10-28 at 11 14 55 am" src="https://cloud.githubusercontent.com/assets/8659273/10798553/7176f990-7d65-11e5-90cd-2d8fe6365169.png">

**Comment by jperez4509** [comment]
@rodneystrong I have been trying to figure out how to actually embed the video but havent found a solution. I even asked Jeremy and Vanessa if they knew of a plugin or anything. The best solution I think will be just create a link to the video: http://www.elocallink.tv/clients3/ca/cloviscoc2014/tourplay.php?movie=cacl14_wel_rev1_iwd&spon=welcome

**Comment by rodneystrong** [comment]
Got the calendar creds and got the API key.
I'll DM it to you in Slack

**Comment by jperez4509** [comment]
Thanks Calendar has been added to the Calendar page and a section has been created in the home. I have completed all of the task on this issue except Twitter. We are still waiting on the Twitter API.

**Comment by jperez4509** [comment]
@rodneystrong: The client keeps mentioning that they like parallax affect and I want to give them what they want. I have tried making the video position absolute and display fixed but this makes it disappear. Can you help me with making the video have a parallax affect?

**Comment by jperez4509** [comment]
1. Done
2. Done 
3. Done
4. Done
5. Done
6. I am not able to embed the COC Tourbook because it is a flash video. However I can create a section where I can link it.

**Comment by rodneystrong** [comment]
That no. 6 isn't flash homie. Those are just external links that pop up a flash player. Just recreate that widget thing and then link to the external flash videos the same way.

**Comment by jperez4509** [comment]
All of this has been completed. I just need to go over site and fix the responsiveness.

**Comment by rodneystrong** [comment]
Nice!

**Comment by jperez4509** [comment]
DONE. This site should be completely responsive.

**Comment by rodneystrong** [comment]
good job sir. i like the decisions you made on repositioning different elements for certain media queries.
