### ISSUE TITLE
Query from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-mtsclovischamber#4]
>Hi Alex,

Is it possible to create a page for Chamber Insider that allows us to embed the current issue? - Perhaps even archive/display embedded past issues?

http://issuu.com/clovisroundup/docs/chamber_insider_-_nov_2015_final#embed

Let me know, because I think it would be good to have it embedded, rather than sending readers off to RoundUp page. (I'd still like to link to Roundup & give them a shout out, but prefer to keep readers on the Chamber site. 

Thanks,

Shel Moore
CMO & Co-o

@jperez4509  if this is beyond you, then please enlist the help of Richard and @irms and @vanderbeam for initial ideas and possibilities

due:
10-29-15    3p

**Comment by jperez4509** [comment]
I should be able to embed it. Will this be on a new tab? or home page?

**Comment by rodneystrong** [comment]
>Is it possible to **create a page** for Chamber Insider that

New page dude

**Comment by jperez4509** [comment]
Done.

**Comment by rodneystrong** [comment]
god damn joel, good job on this
