### ISSUE TITLE
More updates from Client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-mtsclovischamber#5]
Here are a few more notes on the home page:

1. Can you use the logo I shared on Box.com? It has an additional tagline beneath the logo mark "Serving the Entire Central Valley" and this is critical to the Chamber's positioning.

2. The Chamber just found out it's been awarded inclusion on the newest Top 100 Social Media Friendly Chambers of Commerce. I am attaching an updated badge graphic to use in place of the 2013 version. This is a really big deal as it positions them in the top 5% throughout the nation in social media communication & marketing. (I've also updated the slider graphic to use this new badge - see attached)

3. More internal pages are attached...let me know if you have any questions on these.

Hope you're having an awesome week so far,

Shel Moore
CMO & Co

![cocsocialmediabadge100-2015](https://cloud.githubusercontent.com/assets/539962/10835700/a54fd7ac-7e62-11e5-880b-f983f77a64b3.png)
![updated-join-engage-prosper-slider](https://cloud.githubusercontent.com/assets/539962/10835701/a5505952-7e62-11e5-84d7-d29d5ba4b818.png)

-----

[Internal Web Pages 102815.docx](https://github.com/EditLLC/client-mtsclovischamber/files/23888/Internal.Web.Pages.102815.docx)

due:
10-30-15   5p

**Comment by rodneystrong** [comment]
By the way, the logo she's talkin about is in our google drive. Just look for the logo that has the tagline under it. The current one you're using doesn't have it.

**Comment by jperez4509** [comment]
@rodneystrong: I just saw that the word document where they mention the membership and join page.  On the join page they want a form to create an account. Is there a specific plugin that I need to use? or do I just look for one. On the membership page they want their directory. How do I get access to it or is this another plugin? I just want to make sure I understand before I start on these pages.

**Comment by rodneystrong** [comment]
Use a plugin called Contact Form 7. 

Their directory is going to be accessed through InfusionSoft. Just create a placeholder page for the directory for now and I'll make a separate issue for that.

**Comment by jperez4509** [comment]
This has been done, just need to add a directory plugin for the membership page.
