### ISSUE TITLE
Possible spacing issue

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-mtsclovischamber#6]
Was this intentional? If so, convince me  ;)

<img width="663" alt="screen shot 2015-11-04 at 3 44 51 pm" src="https://cloud.githubusercontent.com/assets/539962/10955763/17778bde-830b-11e5-964a-ef7a4a36b586.png">

due:
11-4-15  11p

**Comment by jperez4509** [comment]
Fixed.
