### ISSUE TITLE
Design and content udpates from client #1

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-mtsclovischamber#8]
>Chamber website notes:
Home page:
1.	Would like some of the text to be animated on sliders – need more oomph in the slider portion of site – and I’ve got to create a new slider to replace Kings River Winery Mixer since we’re in November now. 
2.	Remove space between “Lunch!Connect” on Most Active Chamber slider
3.	Fix “View Event Calendar” button link
4.	Need all social media icons at top right and Chamber phone number (559) 299-7363
a.	https://www.facebook.com/ClovisChamber
b.	https://twitter.com/clovischamber
c.	https://www.linkedin.com/company/clovis-chamber-of-commerce
d.	https://plus.google.com/+Clovischamber/
e.	https://www.pinterest.com/ClovisChamber/
f.	https://instagram.com/clovischamber/
g.	https://www.youtube.com/channel/UCnaD1MoJ25-MtDeqscpYJPA
h.	Also add icons/links to bottom under, “Stay Connected” section.
5.	Can we move the calendar up the page near or combined with the Become A Member section? This is a pretty important feature on the home page…or, can we put a graphic that links to this part of the page where people can jump to this info? I’m open to ideas here, but think we need to tweak the calendar part more…
6.	Close the space in “Clovis Fest” There is no space in this name.
7.	Need to add a link to download the Chamber mobile app (http://clovischamberapp.mobapp.at/landing/Desktop) – might even be worth including the video link here as well. 
8.	The hot air balloon video needs to stay with the BIG Hat Days & ClovisFest info…
9.	I think we will be getting a new YEA video, we will check on this…
10.	The counter is not counting up/down would like this to be more stylized. Clovis EXPO is May 4, 2016
11.	Can we remove the bit in the Twitter widget that says, “via Hootsuite”

due:
11-9-15    5p

**Comment by jperez4509** [comment]
@rodneystrong Working on animating some of the text on the slides, and finding the correct counter for #10. Everything else on this issue has been completed. However, I do want to mention that the Calendar plugin I was using did an update and now looks completely different I am going to try to fix it tonight.

**Comment by jperez4509** [comment]
Done. The calendar is still having some issues. I will fix this tomorrow (hopefully the creator of the plugin does another update that fixes the issues. If not I will just upload previous version.)
