### ISSUE TITLE
Site link structure fixes

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-mtsclovischamber#9]
Structure issue with /how-to-join/ and /directory/ pages - see details below:

1.    The structure here differs from the existing website. We need this to be structured as follows:
a.    Clovischamber.com/membership/  (main directory page)
b.    Clovischamber.com/membership/join (how to join page)
c.    Rename /how-to-join/ page to /membership/join
d.    Rename /directory/ page to /membership/
e.    We need to exactly mimic the existing structure.

Also, go through the whole site and make sure the link structure is the same as the current live site. This is for SEO purposes; so they don't lose search engine indexing when we launch the new site

due:
11-10-15    11a

**Comment by rodneystrong** [comment]
Another link issue found: 

http://www.clovischamber.com/programs/ambassador_corp vs. http://mtsclovischamber.editllc.com/ambassadors/

**Comment by jperez4509** [comment]
Done.
